In [1]:
from sync import sync
sync('/moj.ladisk.si/mojladisksi.py')
from mojladisksi import poslji
import numpy as np


# ING

Kovšca Dejan, 23160187, dejan.kovsca@gmail.com

Pričetek reševanja: Mon Dec 18 18:48:39 UTC 2017

Na sliki je prikazana pot vozila po ravnini. Pospešek v $x$ koordinati je podan z izrazom $p(t) = a\,t^3+b\,t+c$.

<img width=500 src='dejan.kovsca_ING_Mon Dec 18 18-48-39 UTC 2017.jpg'>

In [47]:
a = 0.03 # m/s$^5$
b = 0.2 # m/s$^3$
c = 1.25 # m/s$^2$
i = 210 # 
n = 163 # 
t_2 = 25.6 # s

### 1. vprašanje

 Gaussova kvadratura lahko izračuna integral funkcij s singularnostmi. (1: Da, 2: Ne)

Število poskusov: 1.

In [3]:
odgovor1 = 1#?

In [4]:
poslji(odgovor1, id=835393771229347840, st=0)

Pravilna rešitev. Uspeh: 16%. Preostali čas: 2dni,12ur, 0min


### 2. vprašanje

 Določite numerični integral $\int_{0}^{t_2} p(x)\,dx$ s `scipy.integrate.trapz` pri koraku $t_2/8$.

Število poskusov: 3, enote:  m/s

In [24]:
t = np.arange(0, t_2+t_2/8, t_2/8)
p = np.poly1d([a, 0, b, c])
p_t = p(t)

In [25]:
I1 = np.trapz(p_t, dx=t_2/8)
I1

3369.0931200000009

In [26]:
odgovor2 = I1#?

In [27]:
poslji(odgovor2, id=735393771229347840, st=1)

Pravilna rešitev. Uspeh: 33%. Preostali čas: 2dni,11ur, 43min


### 3. vprašanje

 Določite polje šuma, ki naj bo dolžine $n+1$, z definiranim semenom `i` (uporabite funkciji `numpy.random.seed(i)` in `numpy.random.rand`).Kot rešitev vpišite numerično polje!

Število poskusov: 3.

In [32]:
np.random.seed(i)
polje_suma = np.random.rand(n+1)
polje_suma

array([ 0.09992421,  0.3028481 ,  0.78305981,  0.50438093,  0.11269059,
        0.10244724,  0.86487058,  0.8620894 ,  0.39841309,  0.74786699,
        0.17488995,  0.94362146,  0.05239074,  0.8619607 ,  0.56097136,
        0.87692642,  0.89113946,  0.13905215,  0.25368297,  0.20005128,
        0.79802209,  0.04351079,  0.79494529,  0.85482496,  0.27955901,
        0.12799076,  0.63072751,  0.87332605,  0.35092847,  0.74252247,
        0.39550001,  0.52016361,  0.89645826,  0.1904936 ,  0.7492675 ,
        0.09500778,  0.59788104,  0.99959711,  0.54006444,  0.43153222,
        0.05679058,  0.82165019,  0.28799345,  0.71259992,  0.48733147,
        0.35929439,  0.24059005,  0.00227433,  0.14024303,  0.70832684,
        0.16467687,  0.45023011,  0.35972366,  0.45860706,  0.41145839,
        0.86143667,  0.03718539,  0.52994697,  0.03054952,  0.73891871,
        0.35301889,  0.47751301,  0.47533039,  0.89745649,  0.96557467,
        0.00491663,  0.23205019,  0.5535666 ,  0.57865337,  0.13

In [33]:
odgovor3 = polje_suma#?

In [34]:
poslji(odgovor3, id=635393771229347840, st=2)

Pravilna rešitev. Uspeh: 50%. Preostali čas: 2dni,11ur, 40min


### 4. vprašanje

 Opazovani časovni interval $[0,t_2]$ razdelite na $n$ ekvidistantnih odsekov s korakom $h$. Določite korak $h$.

Število poskusov: 3, enote:  s

In [53]:
t1, h = np.linspace(0, t_2, n+1, retstep=True)

In [54]:
h

0.15705521472392639

In [55]:
odgovor4 = h#?

In [56]:
poslji(odgovor4, id=635393771229347840, st=3)

Pravilna rešitev. Uspeh: 66%. Preostali čas: 2dni,11ur, 35min


### 5. vprašanje

 S kumulativno trapezno metodo (`scipy.integrate.cumtrapz`) izračunajte vrednost integrala pri vseh diskretnih točkah ob uporabi koraka $h$. (Torej: $\int_{0}^{t_i} p(x)\,dx$), kjer je $t_i$ diskretna točka.

Število poskusov: 3, enote:  m/s

In [57]:
from scipy import integrate

In [58]:
I2 = integrate.cumtrapz(y=p(t1), dx=h, initial=0)
I2

array([  0.00000000e+00,   1.98794779e-01,   4.02595837e-01,
         6.11567451e-01,   8.25983412e-01,   1.04622703e+00,
         1.27279114e+00,   1.50627807e+00,   1.74739969e+00,
         1.99697738e+00,   2.25594204e+00,   2.52533407e+00,
         2.80630340e+00,   3.10010949e+00,   3.40812130e+00,
         3.73181730e+00,   4.07278550e+00,   4.43272340e+00,
         4.81343805e+00,   5.21684600e+00,   5.64497329e+00,
         6.09995554e+00,   6.58403782e+00,   7.09957476e+00,
         7.64903050e+00,   8.23497869e+00,   8.86010249e+00,
         9.52719459e+00,   1.02391572e+01,   1.09990020e+01,
         1.18098503e+01,   1.26749328e+01,   1.35975898e+01,
         1.45812711e+01,   1.56295360e+01,   1.67460533e+01,
         1.79346013e+01,   1.91990679e+01,   2.05434505e+01,
         2.19718560e+01,   2.34885007e+01,   2.50977107e+01,
         2.68039213e+01,   2.86116775e+01,   3.05256338e+01,
         3.25505541e+01,   3.46913121e+01,   3.69528906e+01,
         3.93403824e+01,

In [59]:
odgovor5 = I2#?

In [60]:
poslji(odgovor5, id=835393771229347840, st=4)

Pravilna rešitev. Uspeh: 83%. Preostali čas: 2dni,11ur, 31min


### 6. vprašanje

 Ponovno določite numerični integral s kumulativno trapezno metodo (`scipy.integrate.cumtrapz`), vendar še z dodanim šumom $p(t)=a\,t^3+b\,t+c+\textrm{sum}$. Kot rešitev podajte numerično polje vrednosti integrala v teh točkah.

Število poskusov: 3, enote:  m/s

In [65]:
def p2(x, pojle_suma):
    p = 0.03*x**3 + 0.2*x + 1.25
    return p + polje_suma

In [66]:
I3 = integrate.cumtrapz(y=p2(t1, polje_suma), dx=h, initial=0)
I3

array([  0.00000000e+00,   2.30423525e-01,   5.19498333e-01,
         8.29569587e-01,   1.09244270e+00,   1.32958058e+00,
         1.63210583e+00,   2.00120680e+00,   2.34131267e+00,
         2.68090499e+00,   3.01233154e+00,   3.36955760e+00,
         3.72874139e+00,   4.09434931e+00,   4.51410056e+00,
         4.95071124e+00,   5.43052142e+00,   5.87135781e+00,
         6.28291300e+00,   6.72195161e+00,   7.22845522e+00,
         7.74952103e+00,   8.29944526e+00,   8.94453472e+00,
         9.58307091e+00,   1.02010230e+01,   1.08857271e+01,
         1.16709290e+01,   1.24790294e+01,   1.33247403e+01,
         1.42249548e+01,   1.51619421e+01,   1.61958431e+01,
         1.72648801e+01,   1.83869421e+01,   1.95697583e+01,
         2.08127172e+01,   2.22026300e+01,   2.36679185e+01,
         2.51726212e+01,   2.67276127e+01,   2.84058045e+01,
         3.01991528e+01,   3.20854832e+01,   3.40936672e+01,
         3.61850711e+01,   3.83729365e+01,   4.06535867e+01,
         4.30522699e+01,

In [67]:
odgovor6 = I3#?

In [68]:
poslji(odgovor6, id=735393771229347840, st=5)

Pravilna rešitev. Uspeh: 100%. Preostali čas: 2dni,11ur, 26min
