In [1]:
from sync import sync
sync('/moj.ladisk.si/mojladisksi.py')
from mojladisksi import poslji
import numpy as np

# SLE

Kovšca Dejan, 23160187, dejan.kovsca@gmail.com

Pričetek reševanja: Tue Nov 07 20:46:05 UTC 2017

Prikazan je tokokrog z dvema zankama $z_1$ in $z_2$, ter z dvema vozliščema $k_1$ in $k_2$. Enačbe v tokokrogih postavimo s pomočjo Kirchhoffovega tokovnega zakona (vsota tokov v vozliščih je enaka nič) in Kirchhoffovega napetostnega zakona  (padec napetosti v zanki je enak gonilni napetosti). Napetost na uporih izračunamo po Ohmovem zakonu ($u=i\,R$). 

<img width=500 src='dejan.kovsca_SLE_Tue Nov 07 20-46-05 UTC 2017.jpg'>

In [ ]:
i_1 - i_2 + i_3 = 0 #Kirchhoffov tokovni zakon k1
-u_1 + R_1*i_1 + R_3*i_2 -u_2 + R_4*i_1 = 0 #z1
-u_2 + R_5*i_3 + R_2*i_3 + R_3*i_2 = 0 #z2

In [2]:
R_1 = 90 # Ohm
R_2 = 220 # Ohm
R_3 = 180 # Ohm
R_4 = 290 # Ohm
R_5 = 100 # Ohm
u_1 = 30 # V
u_2 = 140 # V

### 1. vprašanje

 Pri LU razcepu dobimo zgorne trikotno in spodnje trikotno matriko. (1: Da, 2: Ne)

Število poskusov: 1.

In [2]:
odgovor1 = 1#?

In [3]:
poslji(odgovor1, id=505560641741914112, st=0)

Pravilna rešitev. Uspeh: 100%. Preostali čas: 2dni,15ur, 55min


### 2. vprašanje

 Podani so upori $R_1$, $R_2$, $R_3$, $R_4$, $R_5$ in gonilni napetosti $u_1$ in $u_2$. Nastavite sistem linarnih enačb v križišču $k_1$ in zankah $z_1$ in $z_2$. Tukaj najprej vpišite vektor neznank (kot string, ločene z vejico, abecedni vrstni red). 

Število poskusov: 3, enote:  A, A, A

In [ ]:
i_1 - i_2 + i_3 = 0 #Kirchhoffov tokovni zakon k1
-u_1 + R_1*i_1 + R_3*i_2 -u_2 + R_4*i_1 = 0 #z1
-u_2 + R_5*i_3 + R_2*i_3 + R_3*i_2 = 0 #z2

In [3]:
vektor_neznank = 'i_1, i_2, i_3'

In [4]:
odgovor2 = vektor_neznank#?
odgovor2

'i_1, i_2, i_3'

In [35]:
poslji(odgovor2, id=605560641741914112, st=1)

Pravilna rešitev. Uspeh: 33%. Preostali čas: 8dni,9ur, 38min


### 3. vprašanje

 Določite matriko koeficientov! Zaradi enoličnosti rešitve naj bodo na diagonali koeficienti $[1,R_3,R_2+R_5]$

Število poskusov: 3, enote:  Po vrsticah: 1, Ohm, Ohm

In [ ]:
i_1 - i_2 + i_3 = 0 #Kirchhoffov tokovni zakon k1
-u_1 + R_1*i_1 + R_3*i_2 -u_2 + R_4*i_1 = 0 #z1
-u_2 + R_5*i_3 + R_2*i_3 + R_3*i_2 = 0 #z2

In [5]:
A = np.array([[1, -1, 1],
             [R_1+R_4, R_3, 0],
             [0, R_3, R_2+R_5]])

In [6]:
odgovor3 = A#?
odgovor3

array([[  1,  -1,   1],
       [380, 180,   0],
       [  0, 180, 320]])

In [7]:
poslji(odgovor3, id=105560641741914112, st=2)

Pravilna rešitev. Uspeh: 50%. Preostali čas: 7dni,14ur, 25min


### 4. vprašanje

 Določite vektor konstant!

Število poskusov: 3, enote:  A,V,V

In [ ]:
i_1 - i_2 + i_3 = 0 #Kirchhoffov tokovni zakon k1
-u_1 + R_1*i_1 + R_3*i_2 -u_2 + R_4*i_1 = 0 #z1
-u_2 + R_5*i_3 + R_2*i_3 + R_3*i_2 = 0 #z2

In [8]:
b = np.array([0, u_1+u_2, u_2])

In [9]:
odgovor4 = b#?
odgovor4

array([  0, 170, 140])

In [29]:
poslji(odgovor4, id=405560641741914112, st=3)

Pravilna rešitev. Uspeh: 16%. Preostali čas: 8dni,9ur, 41min


### 5. vprašanje

 Določite rešitev sistema linearnih enačb.

Število poskusov: 3, enote:  A, A, A

In [10]:
x = np.linalg.solve(A, b)

In [11]:
odgovor5 = x#?
odgovor5

array([ 0.24151858,  0.43457189,  0.19305331])

In [12]:
poslji(odgovor5, id=805560641741914112, st=4)

Pravilna rešitev. Uspeh: 66%. Preostali čas: 7dni,14ur, 24min


### 6. vprašanje

 Določite skalarni produkt prve in tretje vrstice matrike koeficientov!

Število poskusov: 3.

In [13]:
skalarni = A[0] @ A[2]

In [14]:
odgovor6 = skalarni#?
odgovor6

140

In [15]:
poslji(odgovor6, id=305560641741914112, st=5)

Pravilna rešitev. Uspeh: 83%. Preostali čas: 7dni,14ur, 23min
