In [1]:
from sync import sync
sync('/moj.ladisk.si/mojladisksi.py')
from mojladisksi import poslji
import numpy as np
;

''

# DEZ

Kovšca Dejan, 23160187, dejan.kovsca@gmail.com

Pričetek reševanja: Thu Dec 28 17:37:52 UTC 2017

Opazujete padanje verige preko roba, ki je popisano z gibalno enačbo: $$l\,\ddot{x}(t) - g\,x(t)\,(\mu+1)=-l\,g\,\mu,$$kjer je $l$ celotna dolžina verige, $g$ gravitacijski pospešek in $\mu$ koeficient trenja. Padanje verige opazujemo v $n$ ekvidistančno razporejenih točkah v časovnem intervalu $t\in[t_0,\, t_1]$.

<img width=500 src='dejan.kovsca_DEZ_Thu Dec 28 17-37-52 UTC 2017.jpg'>

In [2]:
mu = 0.15000000000000002 # /
g = 9.81 # m/s$^2$
l = 0.55 # m
n = 2000 # /
t_0 = 0.03 # s
t_1 = 0.1 # s
x_0 = 0.35 # m

### 1. vprašanje

 Navadne diferencialne enačbe so sestavljene iz funkcije z več spremenljivami in iz njenih odvodov (1: Da, 2: Ne).

Število poskusov: 1, enote:  /

In [3]:
odgovor1 = 2#?

In [4]:
poslji(odgovor1, id=605329093518163968, st=0)

Pravilna rešitev. Uspeh: 20%. Preostali čas: 6dni,13ur, 38min


### 2. vprašanje

 Določite numerično polje časa $t$.

Število poskusov: 3, enote:  s

In [3]:
t = np.linspace(t_0, t_1, n)
t[:10]

array([ 0.03      ,  0.03003502,  0.03007004,  0.03010505,  0.03014007,
        0.03017509,  0.03021011,  0.03024512,  0.03028014,  0.03031516])

In [6]:
odgovor2 = t#?

In [7]:
poslji(odgovor2, id=205329093518163968, st=1)

Pravilna rešitev. Uspeh: 40%. Preostali čas: 6dni,13ur, 36min


### 3. vprašanje

 S pomočjo funkcije `scipy.integrate.odeint` rešite diferencialno enačbo in določite numerično polje pomikov ${x}(t)$.  Za začetne pogoje uporabite $x(t_0) = x_0$ in $\dot{x}(t_0) = 0$.

Število poskusov: 3, enote:  m

In [4]:
from scipy.integrate import odeint

In [5]:
def fun(y, t, g=9.81, l=0.55, mu = 0.15000000000000002):
    x, vx = y #x=x, vx=x'
    return np.array([vx, g*(mu+1)*x/l - g*mu])

In [6]:
y0 = np.array([x_0, 0]) #pogoji: [x, x']

In [7]:
x_vx_odeint = odeint(fun, y0=y0, t=t)
x_vx_odeint[:5]  #[x, x']

array([[  3.50000000e-01,   0.00000000e+00],
       [  3.50000004e-01,   1.99867225e-04],
       [  3.50000014e-01,   3.99734510e-04],
       [  3.50000032e-01,   5.99601854e-04],
       [  3.50000056e-01,   7.99469258e-04]])

In [8]:
x_odeint = x_vx_odeint[:, 0] #prvi stolpec so poti x(t)
x_odeint[:5]

array([ 0.35      ,  0.35      ,  0.35000001,  0.35000003,  0.35000006])

In [9]:
odgovor3 = x_odeint#?
odgovor3[:10]

array([ 0.35      ,  0.35      ,  0.35000001,  0.35000003,  0.35000006,
        0.35000009,  0.35000013,  0.35000017,  0.35000022,  0.35000028])

In [22]:
poslji(odgovor3, id=505329093518163968, st=2)

Pravilna rešitev. Uspeh: 60%. Preostali čas: 6dni,12ur, 57min


### 4. vprašanje

 Določite še numerično polje pospeškov $\ddot{x}(t)$.

Število poskusov: 3, enote:  m/s$^2$

In [10]:
vvx_odeint = g*(mu+1)*x_odeint/l - g*mu

In [11]:
odgovor4 = vvx_odeint#?
odgovor4[:10]

array([ 5.70763636,  5.70763644,  5.70763665,  5.70763701,  5.70763751,
        5.70763816,  5.70763895,  5.70763988,  5.70764096,  5.70764218])

In [28]:
poslji(odgovor4, id=105329093518163968, st=3)

Pravilna rešitev. Uspeh: 80%. Preostali čas: 6dni,12ur, 51min


### 5. vprašanje

 Za primerjavo določite numerično polje pospeškov $\ddot{x}(t)$ še s pomočjo funkcije `scipy.integrate.ode` (uporabite integrator `vode`).

Število poskusov: 3, enote:  m/s$^2$

In [55]:
from scipy.integrate import ode

In [56]:
def fun_ode(t, y, g=9.81, l=0.55, mu = 0.15000000000000002):
    x, vx = y #x=x, vx=x'
    return np.array([vx, g*(mu+1)*x/l - g*mu])

In [57]:
x_ode = ode(fun_ode)
x_ode.set_integrator('vode')
x_ode.set_initial_value(y0, t=t)
x_ode.set_f_params(9.81, 0.55, 0.15000000000000002)

In [58]:
x_ode_rezultat = np.zeros_like(t)
for i, cas in enumerate(t[1:]):
    x_ode_rezultat[i+1] = x_ode.integrate(cas)[0]
x_ode_rezultat1 = np.hstack((x_0, x_ode_rezultat[1:])) 
x_ode_rezultat1[:10]

array([ 0.35      ,  0.35000001,  0.35000002,  0.35000005,  0.35000009,
        0.35000013,  0.35000017,  0.35000022,  0.35000027,  0.35000033])

In [59]:
vvx_ode_rezultat = g*(mu+1)*x_ode_rezultat1/l - g*mu
vvx_ode_rezultat[:10]

array([ 5.70763636,  5.7076365 ,  5.70763678,  5.70763735,  5.70763819,
        5.70763903,  5.70763987,  5.7076408 ,  5.70764188,  5.7076431 ])

In [60]:
odgovor5 = vvx_ode_rezultat#?

In [61]:
poslji(odgovor5, id=505329093518163968, st=4)

Pravilna rešitev. Uspeh: 100%. Preostali čas: 14ur, 23min, 43s


In [53]:
x_ode_rezultat

array([ 0.        ,  0.35000001,  0.35000002, ...,  0.36407316,
        0.36408737,  0.3641016 ])

In [54]:
x_ode_rezultat1

array([ 0.35      ,  0.35000001,  0.35000002, ...,  0.36407316,
        0.36408737,  0.3641016 ])