In [1]:
from sync import sync
sync('/moj.ladisk.si/mojladisksi.py')
from mojladisksi import poslji
import numpy as np
;

''

# ODV

Kovšca Dejan, 23160187, dejan.kovsca@gmail.com

Pričetek reševanja: Mon Dec 11 14:55:03 UTC 2017

Med letom s športnim letalom ste naleteli na turbulenco. Po pristanku ste si ogledali meritve vaše nadmorske višine in ugotovili, da jo lahko v času turbulence aproksimirate z izrazom $y(t) = A - H \sin(k \pi t \, / \, (t_2-t_1))$.

<img width=500 src='dejan.kovsca_ODV_Mon Dec 11 14-55-03 UTC 2017.jpg'>

In [2]:
A = 450 # m
H = 21.5 # m
k = 2.7 # 
N = 120 # 
t_1 = 5.25 # s
t_2 = 8.5 # s

### 1. vprašanje

 Natančnost zapisa števil v spominu nima vpliva na napako numeričnega odvajanja! (1: Da, 2: Ne)

Število poskusov: 1.

In [3]:
odgovor1 = 2#?

In [4]:
poslji(odgovor1, id=626632659511934976, st=0)

Pravilna rešitev. Uspeh: 20%. Preostali čas: 2dni,16ur, 19min


### 2. vprašanje

 Pripravite numerično polje časa ``t`` z $N$ ekvidistantnimi točkami na intervalu $[t_1, t_2]$ in izračunajte numerično polje ``y`` pripadajočih vrednosti nadmorske višine $y(t)$. Kot odgovor podajte numerično polje ``y``.

Število poskusov: 3, enote:  m

In [20]:
t, h = np.linspace(t_1, t_2, N, retstep=1)
y = A - H * np.sin(k * np.pi * t / (t_2 - t_1))

In [6]:
odgovor2 = y#?
odgovor2

array([ 430.50220124,  429.90645524,  429.41275759,  429.02361563,
        428.74100567,  428.56636299,  428.50057455,  428.54397447,
        428.69634232,  428.95690429,  429.32433706,  429.79677458,
        430.37181749,  431.04654533,  431.8175314 ,  432.68086011,
        433.63214692,  434.66656054,  435.77884755,  436.96335901,
        438.21407919,  439.52465609,  440.88843375,  442.29848598,
        443.74765162,  445.22857083,  446.73372253,  448.25546255,
        449.78606249,  451.31774895,  452.842743  ,  454.35329972,
        455.84174749,  457.30052699,  458.72222957,  460.09963488,
        461.42574754,  462.69383267,  463.89745009,  465.03048703,
        466.08718918,  467.06218991,  467.95053751,  468.74772037,
        469.44968986,  470.05288091,  470.55423012,  470.95119131,
        471.24174845,  471.42442588,  471.49829586,  471.46298322,
        471.31866731,  471.06608105,  470.70650725,  470.24177207,
        469.67423572,  469.00678055,  468.24279633,  467.38616

In [7]:
poslji(odgovor2, id=726632659511934976, st=1)

Pravilna rešitev. Uspeh: 40%. Preostali čas: 2dni,16ur, 14min


### 3. vprašanje

 Z uporabo funkcije ``numpy.gradient`` numerično izračunajte hitrost letala v navpični smeri $\dot{y}$ v času $[t_1, t_2]$.

Število poskusov: 3, enote:  m/s

In [8]:
v = np.gradient(y, t)

array([-21.81346906, -19.94519912, -16.16275592, -12.29822752,
        -8.37124056,  -4.40173887,  -0.40988224,   3.58405605,
         7.55979212,  11.49713455,  15.37608689,  19.17694927,
        22.88041836,  26.4676855 ,  29.92053217,  33.22142252,
        36.35359243,  39.30113466,  42.04907965,  44.5834715 ,
        46.89143889,  48.96126042,  50.78242418,  52.34568107,
        53.64309186,  54.66806741,  55.41540223,  55.88130086,
        56.06339714,  55.96076629,  55.57392951,  54.90485143,
        53.95693008,  52.73497961,  51.24520592,  49.49517505,
        47.49377483,  45.2511697 ,  42.77874909,  40.0890696 ,
        37.1957912 ,  34.11360788,  30.85817302,  27.44601988,
        23.89447762,  20.22158335,  16.44599046,  12.58687391,
         8.66383286,   4.69679111,   0.70589594,  -3.28858423,
        -7.2663628 , -11.20723794, -15.0911953 , -18.89850955,
       -22.60984462, -26.2063519 , -29.66976592, -32.98249718,
       -36.12772142, -39.08946512, -41.85268656, -44.40

In [9]:
odgovor3 = v#?

In [10]:
poslji(odgovor3, id=226632659511934976, st=2)

Pravilna rešitev. Uspeh: 60%. Preostali čas: 2dni,16ur, 12min


### 4. vprašanje

 Hitrost v navpični smeri v diskretnih točkah, kjer je to mogoče, numerično izračunajte še z uporabo diferenčne sheme naprej z redom napake $\mathcal{O}(h^{2})$. Kot rezultat podajte izračunane vrednosti odvoda v prvih $N-2$ točkah.

Število poskusov: 3, enote:  m/s

In [25]:
def diferenčnashema_prvi(y, h):
    v_diferenčna = []
    for i in range(len(y)-2):
        v = (1/(2*h)) * (-3*y[i] + 4*y[i+1] -y[i+2])
        v_diferenčna.append(v)
    return v_diferenčna 

In [30]:
v_diferenčna = np.array(diferenčnashema_prvi(y, h))
odgovor4 = v_diferenčna#?
odgovor4

array([-23.681739  , -19.99110245, -16.1989378 , -12.3245042 ,
        -8.38747859,  -4.40785579,  -0.40584698,   3.598223  ,
         7.58401881,  11.53129794,  15.42001348,  19.23041596,
        22.94315362,  26.53937072,  30.00080328,  33.30987184,
        36.44977077,  39.40455357,  42.15921388,  44.69976173,
        47.01329451,  49.08806258,  50.91352888,  52.48042249,
        53.78078567,  54.80801433,  55.55689151,  56.02361392,
        56.20581123,  56.10255812,  55.71437898,  55.04324524,
        54.09256537,  52.86716755,  51.37327515,  49.61847517,
        47.61167963,  45.36308038,  42.88409729,  40.1873203 ,
        37.28644542,  34.19620521,  30.93229398,  27.51128803,
        23.95056149,  20.26819811,  16.48289936,  12.61388951,
         8.68081795,   4.70365944,   0.70261262,  -3.30200253,
        -7.28984792, -11.24067062, -15.13440573, -18.95127829,
       -22.67190368, -26.27738609, -29.74941449, -33.07035562,
       -36.22334353, -39.19236526, -41.96234214, -44.51

In [31]:
v[56]

-22.609844621374577

In [32]:
v_diferenčna[56]

-22.671903677911768

In [33]:
poslji(odgovor4, id=726632659511934976, st=3)

Pravilna rešitev. Uspeh: 80%. Preostali čas: 2dni,15ur, 52min


### 5. vprašanje

 Z uporabo diferenčne sheme naprej z redom napake $\mathcal{O}(h^{2})$ numerično določite še pospešek letala v navpični smeri $\ddot{y}$. Kot rezultat podajte izračunane vrednosti 2. odvoda v prvih $N-3$ točkah.

Število poskusov: 3, enote:  m/s^2

In [34]:
def diferenčnashema_drugi(y, h):
    a_diferenčna = []
    for i in range(len(y)-3):
        v = (1/(h**2)) * (2*y[i] -5*y[i+1] + 4*y[i+2] -y[i+3])
        a_diferenčna.append(v)
    return a_diferenčna 

In [35]:
a_diferenčna = np.array(diferenčnashema_drugi(y, h))
odgovor5 = a_diferenčna#?
odgovor5

array([ 133.45330907,  137.52675341,  140.90174561,  143.56114522,
        145.49144604,  146.68284472,  147.12929055,  146.82851618,
        145.78204915,  143.9952041 ,  141.47705583,  138.24039316,
        134.301654  ,  129.68084191,  124.40142442,  118.49021392,
        111.97723146,  104.89555429,   97.28114787,   89.17268321,
         80.61134048,   71.64059985,   62.30602069,   52.65501021,
         42.73658264,   32.60111033,   22.30006794,   11.88577101,
          1.41111024,   -9.07071709,  -19.50647729,  -29.84317065,
        -40.02830058,  -50.01014024,  -59.7379952 ,  -69.16246097,
        -78.23567386,  -86.91155406,  -95.1460397 , -102.8973106 ,
       -110.12600065, -116.79539777, -122.87163034, -128.3238392 ,
       -133.12433444, -137.24873593, -140.67609725, -143.38901196,
       -145.37370209, -146.62008807, -147.12183992, -146.8764094 ,
       -145.88504299, -144.15277549, -141.68840452, -138.50444577,
       -134.61706952, -130.04601842, -124.81450733, -118.94910

In [36]:
poslji(odgovor5, id=326632659511934976, st=4)

Pravilna rešitev. Uspeh: 100%. Preostali čas: 2dni,15ur, 47min
