# Sistemi linearnih algebrajskih enačb

Ax = b

x = {x,y}

Sistem dveh enačb:
* 3x-y=8
* 5x = -1


     x   y
A =[[3, -1], [5, 0]]


ax=b -> x=b/a #skalarji

Ax = b -> z leve množimo A⁻¹ #matrike in vektorji

A⁻¹ \* A \* x = A⁻¹ \* b

x = A⁻¹ \* b

In [2]:
import numpy as np

In [4]:
A = np.array([[6, -2],
             [0, 2.5]])
b = np.array([14, 5])
x = np.linalg.solve(A, b)
x

array([ 3.,  2.])

# Enoličnost rešitve

rang = št. linearno neodvisnih enačb v sistemu

rang = št. neničelnih vrstic kanonične oblike (št. pivotov)

[a_00, a_01], [0, a_11] - kanonična oblika

[2, 4 | 6], [1, 2 | 3] - linearno odvisni enačbi! - razširjena matrika

rešitev obstaja -> **rang razšitjene matrike = rang matrike**
* a + 2b = 1
* a + 2b = 3 #nerešljivo!! - rang matrike = 1 , rang razširjene matrike = 2!

**rang = n** (število neznank) - sistem enolično rešljiv

**rang < n** - neskončno rešitev - parametrična rešitev (nedoločen sistem)
* a + 2b = 1
* 0 + 0 = 0

**numpy ne zna rešit prvega in zadnjega primera!! Moramo sami vedeti če je rešitev parametrična ali je sploh ni!!**

In [5]:
np.linalg.matrix_rank(A, tol=None)

2

# Vprašanja

### 1 vprašanje

In [9]:
A = np.array([[2, -5, 0],
            [5, 2.5, 7],
            [-1, 2.5, 0]])
b = np.array([7, 5, -3.5])

In [11]:
np.linalg.solve(A, b) #Singularna matrika!! - ne zna rešit

LinAlgError: Singular matrix

In [12]:
np.linalg.matrix_rank(A)

2

In [16]:
Ab = np.column_stack((A, b))
Ab

array([[ 2. , -5. ,  0. ,  7. ],
       [ 5. ,  2.5,  7. ,  5. ],
       [-1. ,  2.5,  0. , -3.5]])

In [17]:
np.linalg.matrix_rank(Ab) #torej ima parametrično rešitev, neskončno rešitev

2

In [25]:
np.linalg. det(A) #če je det=0 ni rešitve!

0.0

rešitve ni ko se na levi odštejejo vrstice, desno pa ne!

rešitev je neskončno ko se levo in desno odštejejo - ena enačba manj!

### 2 vprašanje

In [18]:
b = np.array([7, 5, 0])

In [19]:
np.linalg.solve(A, b) #ista napaka ampak drugi primer - ni rešitev!!

LinAlgError: Singular matrix

In [20]:
Ab = np.column_stack((A, b))
np.linalg.matrix_rank(Ab)

3

In [22]:
np.linalg.matrix_rank(A)

2

In [27]:
np.linalg. det(A) #če je det=0 ni rešitve! -> skoraj nič = slabo pogojen

0.0

# Pogojenost sistema

slabo pogojen sistem nam lahko na 1mm napake dolžine na 1m -> zelo velika napaka v rešitvi

In [31]:
A = np.array([[1.1, 22, -35],
              [-7, -2.4, 3.5],
              [0.3, 6.6, -10.5]])
b = np.array([3, -0.5, 1.5])

In [32]:
np.linalg.solve(A, b)

array([ -20.,  690.,  433.])

In [33]:
nov_A = A.copy()
nov_A[2, 1] = nov_A[2, 1]*1.001
nov_A

array([[  1.1   ,  22.    , -35.    ],
       [ -7.    ,  -2.4   ,   3.5   ],
       [  0.3   ,   6.6066, -10.5   ]])

In [34]:
np.linalg.solve(nov_A, b) #za spremembo 1 tisočinke se nam spreminjajo rešitve reda x10

array([ -2.30563003,  80.42895442,  50.39716584])

**det(A)** -> 0 slaba pogojenost

Evklidska in Neskončna norma
* np.linalg.norm(A) -> Evklidska norma
* np.linalg.norm(A, np.inf) -> neskončna norma

število pogojenosti
* np.linalg.cond(A)

cond(A) = norm(A) \* norm(A⁻¹)

# Vprašanja

### 3 Vprašanje

In [35]:
def evklidska_norma(A):
    norma = np.sqrt(np.sum(A**2))
    return norma

In [42]:
def stevilo_pogojenosti(A):
    norma_1 = np.sqrt(np.sum(A**2))
    norma_2 = np.sqrt(np.sum(np.linalg.inv(A)**2))
    pogojenost = norma_1 * norma_2
    return pogojenost

In [43]:
def število_pogojenosti(A): #lahko tudi tako preko prej definirane funkcije
    return evklidska_norma(A) * evklidska_norma(np.linalg.inv(A))

In [37]:
A

array([[  1.1,  22. , -35. ],
       [ -7. ,  -2.4,   3.5],
       [  0.3,   6.6, -10.5]])

In [38]:
evklidska_norma(A)

43.944510464903352

In [39]:
np.linalg.norm(A)

43.944510464903345

In [40]:
stevilo_pogojenosti(A)

62229.854320566701

In [47]:
np.linalg.cond(A) #ena druga pogojenost, glej doc string!

61468.956230229385

In [46]:
np.linalg.cond(A, 'fro') #to je naša pogojenost

62229.854320566701

# Gaussova eliminacija

* razširjena matrika
* želimo dobiti pod diagonalo 0
* prištevamo in množimo vrstice!

* [a_00, a_01, a_02 | b_0]
* [a_10, a_11, a_12 | b_1]
* [a_20, a_21, a_22 | b_2]

ko želimo delati ničle v drugi vrstici je prva vrstica pivotna vrstica

* lambda_1 = a_10/a_00   -->   to pomnožimo z prvo vrstico in odštejemo drugi vrstici

# Vprašanja

### 4 vprašanje

In [50]:
def gauss_priprava(A, b):
    Ab = np.column_stack((A, b)) #razširjena matrika
    n = len(b)
    
    for i in range(0, n-1): #zadnja vrstice ni pivotna vrstica ker ni spodaj nobene druge vrstice
        for j in range(i+1, n):
            lam = Ab[j, i]/Ab[i, i] # poračuna lambde
            print(lam)

In [51]:
gauss_priprava(A, b)

-6.36363636364
0.272727272727
-2.75


In [53]:
def gauss_eliminacija(A, b):
    
    Ab = np.column_stack((A, b))
    n = len(b)
    
    for i in range(0, n-1): #i = pivotna vrstica, gremo po pivotnih vrsticah
        for j in range(i+1, n): #j = vse vrstice pod pivotno -> v teji delamo ničlo
            lam = Ab[j, i]/Ab[i, i]
            Ab[j] -= Ab[i]*lam
    return Ab            

In [55]:
gauss_eliminacija(A, b) #eliminirana razširjena matrika

array([[  1.10000000e+00,   2.20000000e+01,  -3.50000000e+01,
          3.00000000e+00],
       [  0.00000000e+00,   1.37600000e+02,  -2.19227273e+02,
          1.85909091e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.38742072e-03,
          6.00753171e-01]])

In [62]:
def gauss_resitev(Ab):
    A = Ab.copy()[:, :-1] #vse vrstice razen zadni stolpec
    b = Ab.copy()[:, -1]
    n = Ab.shape[0] #število vrstic
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1): #prva vrstica je zadnja, zadnja je prva -> korak je -1 #št. vrstic=3, oštevilčenje 0, 1, 2
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
        
    return x

In [56]:
Ab.shape[0]

3

In [63]:
gauss_resitev(gauss_eliminacija(A, b))

array([ -20.,  690.,  433.])